name: Azure Container App Deploy Action
description: Deploys a container image to an Azure Container App.
author: erikbrgn

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  image:
    description: Image to deploy
    required: true
  app-name:
    description: Name of the Container App to deploy to
    required: true
  container-name:
    description:
      The name of the container to target. Sometimes multiple can exist in the
      same Container App resource.
    required: true
  resource-group-name:
    description: Name of the resource group containing the App Service
    required: true
  subscription-id:
    description: 'Azure subscriptionId'
    required: false
  docker-registry-username:
    description: 'Docker registry username'
    required: false
  docker-registry-password:
    description: 'Docker registry password'
    required: false

outputs:
  status:
    description: The status of the deployment
  container-app:
    description: The entire Container App object serialized as JSON

runs:
  using: node20
  main: dist/index.js
